### ISSUE TITLE
Parsing problem when used within css keyframes

### ISSUE THREAD

**Issue by programingjd** [dmarcotte/idea-handlebars#123]
If you use an expression inside a css keyframe definition on the identifier, then you get a bogus error: "'{' expected" on the closing curly bracket.

Example:
```css
@keyframes kf {
 {{t}}% { opacity: 0; }
} <-- error '{' expected
```
